version: '3'

services:

  predict_server:
    container_name: predictapp
    restart: always
    build: ./predictapp
    ports:
      - "8000:8000"
    command: gunicorn -w 3 -b :8000 app:create_app()


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - predictapp